# Generated by Django 3.0.3 on 2020-02-09 10:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='munitipal_land',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('purpose', models.TextField()),
                ('holder', models.TextField()),
                ('square', models.FloatField()),
                ('describe', models.TextField()),
                ('coordinates', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('holder_num', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='spr_type_company',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='spr_type_foundation',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('purpose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='spr_type_stock',
            fields=[
                ('type', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='housing_stock',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
                ('holder', models.TextField()),
                ('square', models.FloatField()),
                ('describe', models.TextField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('floors', models.IntegerField()),
                ('holder_num', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='munactives.spr_type_stock')),
            ],
        ),
        migrations.CreateModel(
            name='foundation',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('holder', models.TextField()),
                ('square', models.FloatField()),
                ('describe', models.TextField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('holder_num', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='munactives.spr_type_foundation')),
            ],
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('holder', models.TextField()),
                ('square', models.FloatField()),
                ('describe', models.TextField()),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('holder_num', models.IntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='munactives.spr_type_company')),
            ],
        ),
    ]
