# Generated by Django 3.0.3 on 2020-02-09 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('munactives', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='coordinates',
            new_name='point',
        ),
    ]
