# Generated by Django 3.0.3 on 2020-03-07 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munactives', '0005_auto_20200307_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
