# Generated by Django 3.0.3 on 2020-03-11 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('munactives', '0006_auto_20200307_1010'),
    ]

    operations = [
        migrations.CreateModel(
            name='holder',
            fields=[
                ('holder_num', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('fio', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='foundation',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='foundation',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='housing_stock',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='housing_stock',
            name='owner_id',
        ),
        migrations.RemoveField(
            model_name='munitipal_land',
            name='holder',
        ),
        migrations.RemoveField(
            model_name='munitipal_land',
            name='owner_id',
        ),
        migrations.DeleteModel(
            name='owner',
        ),
        migrations.AlterField(
            model_name='company',
            name='holder_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='munactives.holder'),
        ),
        migrations.AlterField(
            model_name='foundation',
            name='holder_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='munactives.holder'),
        ),
        migrations.AlterField(
            model_name='housing_stock',
            name='holder_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='munactives.holder'),
        ),
        migrations.AlterField(
            model_name='munitipal_land',
            name='holder_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='munactives.holder'),
        ),
    ]
