# Generated by Django 3.0.3 on 2020-03-11 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('munactives', '0008_remove_company_holder_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='holder_num',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='munactives.holder'),
        ),
    ]
