# Generated by Django 3.0.3 on 2020-03-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munactives', '0009_company_holder_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holder',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
